window.CASE_STUDIES = {
  'website-travel': {
    slug: 'website-travel',
    category: 'Website chuyển đổi',
    title: 'Website Next.js chuẩn SEO cho thương hiệu du lịch',
    subtitle: 'Từ WordPress chậm đến landing chuyển đổi load dưới 1 giây',
    image: 'assets/website-travel-topviet.png',
    client: 'Thương hiệu du lịch &amp; trải nghiệm (NDA)',
    industry: 'Du lịch / Hospitality',
    duration: '6 tuần',
    year: '2025',
    services: ['Discovery', 'UI/UX', 'Next.js 15', 'SEO & Analytics'],
    metrics: [
      { value: '+42%', label: 'Conversion form đặt tour' },
      { value: '<1s', label: 'Thời gian tải trang' },
      { value: '95+', label: 'Điểm Lighthouse Performance' },
      { value: '3×', label: 'Organic traffic sau 90 ngày' },
    ],
    overview: 'Khách hàng vận hành tour inbound/outbound với traffic lớn từ quảng cáo nhưng website WordPress không theo kịp tốc độ scale. Wave Digital thiết kế lại trải nghiệm booking, tối ưu SEO địa phương và chuẩn bị nền tảng AI-friendly để index nội dung trên ChatGPT/Claude.',
    problems: [
      'WordPress + plugin nặng: LCP > 4s, bounce rate cao trên mobile',
      'Form đặt tour rời rạc, không tracking funnel rõ từng bước',
      'SEO kém: không schema, meta trùng lặp, index chậm trang mới',
      'Đội marketing không tự chỉnh landing theo campaign mà không dev',
    ],
    solution: [
      'Workshop 2 buổi: map customer journey, ưu tiên conversion & SEO local',
      'Thiết kế Figma mobile-first, A/B layout hero & form đặt tour',
      'Build Next.js 15 App Router, ISR cho trang điểm đến, edge CDN',
      'Tích hợp GA4 + Meta Pixel + event custom theo từng bước funnel',
      'Handover playbook: team KH tự cập nhật content qua headless CMS',
    ],
    process: [
      { step: 'Tuần 1', title: 'Discovery & Audit', desc: 'Audit WordPress, benchmark đối thủ, KPI baseline.' },
      { step: 'Tuần 2-3', title: 'Design & Review', desc: 'Figma 3 vòng revision, prototype form booking.' },
      { step: 'Tuần 4-5', title: 'Build & QA', desc: 'Next.js, CMS, SEO schema, performance tuning.' },
      { step: 'Tuần 6', title: 'Go-live', desc: 'DNS cutover, monitoring 72h, training team KH.' },
    ],
    tech: ['Next.js 15', 'TypeScript', 'Tailwind CSS', 'Vercel', 'Sanity CMS', 'GA4', 'Meta Pixel', 'Schema.org'],
    results: [
      'Conversion form đặt tour tăng 42% so với baseline 30 ngày trước go-live',
      'LCP trung bình 0.9s (mobile), Core Web Vitals đạt chuẩn Google',
      'Organic impressions tăng 3× sau 90 ngày nhờ schema & internal linking',
      'Đội marketing tự publish landing campaign trong 2h không cần dev',
    ],
    quote: {
      text: 'Website mới load cực nhanh, SEO tốt. Khác hẳn WordPress trước đây — form đặt tour tăng rõ rệt ngay tháng đầu.',
      author: 'Marketing Director',
      company: 'Thương hiệu du lịch (NDA)',
    },
    related: ['website-ecommerce', 'launching-startup', 'marketing-fmcg'],
  },

  'marketing-fmcg': {
    slug: 'marketing-fmcg',
    category: 'AI Marketing',
    title: 'Chiến dịch content AI cho thương hiệu FMCG',
    subtitle: 'Master Plan 3 tháng — 16 assets đồng bộ, giảm 60% chi phí sản xuất',
    image: 'https://images.shadcnspace.com/assets/blocks-images/marketing/portfolio-section.webp',
    client: 'Nhãn hàng FMCG tiêu dùng nhanh (NDA)',
    industry: 'FMCG / Consumer Goods',
    duration: '12 tuần',
    year: '2025',
    services: ['Master Plan', 'Content AI', 'Paid Media Setup', 'Báo cáo KPI'],
    metrics: [
      { value: '-60%', label: 'Chi phí sản xuất content' },
      { value: '5×', label: 'Số asset / timeline' },
      { value: '+38%', label: 'Engagement rate trung bình' },
      { value: '2.1×', label: 'ROAS campaign launch' },
    ],
    overview: 'Nhãn hàng ra mắt dòng sản phẩm mới cần đồng bộ hình ảnh, video social và TVC trong 3 tháng nhưng ngân sách inhouse và studio truyền thống không đủ. Wave Digital xây Master Plan, sản xuất bằng AI có kiểm duyệt brand và vận hành ads đa kênh.',
    problems: [
      'Timeline gấp: 16 assets (8 image, 8 video) trong 8 tuần sản xuất',
      'Chi phí studio truyền thống vượt 60% ngân sách marketing',
      'Thiếu pillar content thống nhất giữa Meta, TikTok và retail',
      'Không có dashboard KPI real-time cho leadership',
    ],
    solution: [
      'Master Plan Notion: persona, messaging, content calendar 12 tuần',
      'Mood board & brand guardrails duyệt trước khi generate AI',
      'Pipeline Midjourney + Runway + ElevenLabs với 2 vòng revision/asset',
      'Setup Meta & TikTok ads, UTM chuẩn, weekly report CAC/ROAS',
    ],
    process: [
      { step: 'Tuần 1-2', title: 'Strategy', desc: 'Workshop, competitor scan, content pillars.' },
      { step: 'Tuần 3-4', title: 'Pre-production', desc: 'Mood board, storyboard TVC, script approval.' },
      { step: 'Tuần 5-8', title: 'AI Production', desc: 'Batch image/video, QA brand, deliver HD/4K.' },
      { step: 'Tuần 9-12', title: 'Launch & Optimize', desc: 'Go-live ads, A/B creative, weekly optimization.' },
    ],
    tech: ['Midjourney', 'Runway Gen-3', 'ElevenLabs', 'CapCut', 'Meta Ads', 'TikTok Ads', 'Notion', 'Looker Studio'],
    results: [
      'Giảm 60% chi phí sản xuất so với báo giá studio truyền thống',
      'Deliver 5× số asset trong cùng timeline so với team inhouse 4 người',
      'ROAS campaign launch đạt 2.1× trong 30 ngày đầu',
      'Leadership có dashboard KPI cập nhật hàng tuần, minh bạch 100%',
    ],
    quote: {
      text: 'Trước đây phải thuê 3 agency khác nhau. Giờ chỉ cần Wave Digital — tiết kiệm cả thời gian lẫn chi phí, content vẫn đúng brand.',
      author: 'Brand Manager',
      company: 'FMCG (NDA)',
    },
    related: ['launching-startup', 'marketing-realestate', 'website-travel'],
  },

  'agent-fintech': {
    slug: 'agent-fintech',
    category: 'AI Agent',
    title: 'Agent chăm sóc khách hàng 24/7 cho fintech',
    subtitle: 'Tự động hóa inbox FB/Zalo — 60%+ tin nhắn xử lý bởi AI',
    image: 'https://images.shadcnspace.com/assets/blocks-images/marketing/feature-section-13.webp',
    client: 'Công ty fintech / ví điện tử (NDA)',
    industry: 'Fintech',
    duration: '8 tuần',
    year: '2025',
    services: ['AI Agent', 'Workflow n8n', 'CRM Integration', 'Human Handoff'],
    metrics: [
      { value: '60%+', label: 'Tin nhắn AI xử lý' },
      { value: '-50%', label: 'Thời gian phản hồi' },
      { value: '+35%', label: 'Lead qualified / tháng' },
      { value: '4.7/5', label: 'CSAT sau triển khai' },
    ],
    overview: 'Fintech scale user nhanh nhưng đội CS 12 người không đủ trả lời inbox Facebook & Zalo OA, đặc biệt ngoài giờ hành chính. Wave Digital triển khai AI Agent đa kênh với knowledge base sản phẩm, qualify lead và chuyển human khi cần.',
    problems: [
      'SLA phản hồi > 4 giờ, khách bỏ giữa chừng khi onboarding ví',
      '60% câu hỏi lặp lại: phí, hạn mức, KYC, khuyến mãi',
      'CRM và inbox tách rời — mất data khi chuyển nhân viên',
      'Không đo được conversion từ chat sang đăng ký thành công',
    ],
    solution: [
      'Knowledge base từ FAQ, policy, script CS hiện tại (RAG)',
      'Agent Claude + workflow n8n: FB Messenger, Zalo OA webhook',
      'Lead scoring & đặt lịch call với sales, sync HubSpot CRM',
      'Human-in-the-loop: escalate KYC phức tạp, fraud, complaint',
    ],
    process: [
      { step: 'Tuần 1-2', title: 'Audit & Design', desc: 'Map intent, flow chart, compliance review.' },
      { step: 'Tuần 3-5', title: 'Build Agent', desc: 'RAG, prompts, test 200+ scenarios.' },
      { step: 'Tuần 6', title: 'Pilot', desc: '20% traffic, monitor hallucination & CSAT.' },
      { step: 'Tuần 7-8', title: 'Scale', desc: '100% inbox, training CS, playbook handoff.' },
    ],
    tech: ['Claude API', 'OpenAI Embeddings', 'n8n', 'Zalo OA API', 'Meta Graph API', 'HubSpot', 'PostgreSQL', 'Vercel'],
    results: [
      'Hơn 60% tin nhắn được xử lý end-to-end bởi agent',
      'Thời gian phản hồi trung bình giảm 50% (từ 4h xuống <2h)',
      'Lead qualified tăng 35%, pipeline sales đồng bộ realtime CRM',
      'CSAT 4.7/5, đội CS tập trung case phức tạp thay vì FAQ',
    ],
    quote: {
      text: 'AI Agent của Wave Digital giúp tụi mình tự động hóa 70% công việc chăm sóc khách hàng — đặc biệt ban đêm vẫn có phản hồi tức thì.',
      author: 'Head of Customer Success',
      company: 'Fintech (NDA)',
    },
    related: ['agent-education', 'custom-logistics', 'marketing-fmcg'],
  },

  'custom-logistics': {
    slug: 'custom-logistics',
    category: 'Custom AI',
    title: 'Pipeline automation tích hợp CRM cho logistics',
    subtitle: 'Agent + workflow — báo giá & tracking đơn tự động',
    image: 'https://images.shadcnspace.com/assets/blocks-images/dashboard/charts-blocks.webp',
    client: 'Doanh nghiệp logistics B2B (NDA)',
    industry: 'Logistics / Supply Chain',
    duration: '10 tuần',
    year: '2025',
    services: ['Custom Agent', 'API Integration', 'CRM Workflow', 'Ops Dashboard'],
    metrics: [
      { value: '-50%', label: 'Xử lý đơn thủ công' },
      { value: '85%', label: 'KH mở rộng scope 6 tháng' },
      { value: '<3 phút', label: 'Báo giá tự động' },
      { value: '99.2%', label: 'Độ chính xác tracking sync' },
    ],
    overview: 'Công ty logistics nhận hàng trăm RFQ/ngày qua email và Zalo, nhân viên nhập tay vào CRM gây trễ báo giá và sai tracking. Wave Digital xây pipeline AI đọc yêu cầu, báo giá theo rule, sync trạng thái đơn và cảnh báo exception.',
    problems: [
      'Báo giá thủ công mất 2–4 giờ/đơn, mất khách vào tay đối thủ',
      'Tracking cập nhật chậm 1–2 ngày, khách hàng B2B phàn nàn',
      'Dữ liệu nằm rải rác: Excel, CRM cũ, email — không single source',
      'Không scale được khi volume tăng gấp đôi mùa cao điểm',
    ],
    solution: [
      'Agent parse RFQ từ email/Zalo → structured quote request',
      'Rules engine + API bảng giá: draft báo giá trong <3 phút',
      'Sync CRM ↔ WMS: tracking realtime, webhook exception',
      'Dashboard ops: queue, SLA, human approve quote > ngưỡng',
    ],
    process: [
      { step: 'Tuần 1-2', title: 'Process Mapping', desc: 'Shadow ops team, data model, API inventory.' },
      { step: 'Tuần 3-6', title: 'Integration', desc: 'CRM, WMS, n8n workflows, agent training.' },
      { step: 'Tuần 7-8', title: 'UAT', desc: 'Pilot 50 đơn/ngày, accuracy tuning.' },
      { step: 'Tuần 9-10', title: 'Production', desc: 'Full rollout, SOP, on-call 2 tuần.' },
    ],
    tech: ['Claude API', 'n8n', 'PostgreSQL', 'REST APIs', 'Zalo OA', 'Custom CRM Bridge', 'Grafana', 'Docker'],
    results: [
      'Giảm 50% thời gian xử lý đơn thủ công cho team ops',
      'Báo giá tự động trả trong <3 phút với 92% case không cần sửa',
      'Tracking sync 99.2% accuracy, giảm ticket hỏi trạng thái',
      '85% khách hàng mở rộng scope thêm module trong 6 tháng',
    ],
    quote: {
      text: 'Wave Digital không chỉ là vendor — họ map đúng quy trình logistics của mình và build hệ thống chạy ổn định qua mùa peak.',
      author: 'COO',
      company: 'Logistics B2B (NDA)',
    },
    related: ['agent-fintech', 'website-ecommerce', 'launching-startup'],
  },

  'launching-startup': {
    slug: 'launching-startup',
    category: 'Launching trọn bộ',
    title: 'Startup tech Launching sản phẩm trong 30 ngày',
    subtitle: 'Website + Master Plan + content AI + ads — một đối tác duy nhất',
    image: 'https://images.shadcnspace.com/assets/shadcnspace-product/templates/digital-arc/digital-arc-01.webp',
    client: 'Startup SaaS B2B (NDA)',
    industry: 'Technology / SaaS',
    duration: '30 ngày',
    year: '2025',
    services: ['Launching trọn bộ', 'Website', 'AI Marketing', 'Go-live Ads'],
    metrics: [
      { value: '30', label: 'Ngày go-live' },
      { value: '1', label: 'Đối tác duy nhất' },
      { value: '240+', label: 'Lead qualified tháng đầu' },
      { value: '-55%', label: 'So với thuê 3 vendor riêng' },
    ],
    overview: 'Startup pre-seed cần ra mắt MVP và landing trong 1 tháng trước khi hết runway marketing. Wave Digital gói Launching: discovery, website Next.js, 8 content AI, setup ads và tracking đầy đủ — một timeline, một đầu mối.',
    problems: [
      'Founder không có đội marketing, chỉ 1 dev full-time',
      'Không thể thuê riêng agency web + content + ads — vượt budget',
      'Cần social proof & landing chuyên nghiệp để pitch investor',
      'Timeline cứng 30 ngày trước demo day',
    ],
    solution: [
      'Discovery workshop 2 buổi: ICP, positioning, KPI launch',
      'Landing Next.js + waitlist + demo booking Cal.com',
      '8 image + 4 video AI, LinkedIn & Meta campaign',
      'Weekly Loom update — founder luôn nắm tiến độ',
    ],
    process: [
      { step: 'Ngày 1-7', title: 'Discovery', desc: 'Brief, persona, wireframe, tech spec.' },
      { step: 'Ngày 8-18', title: 'Build & Content', desc: 'Website live preview, batch content AI.' },
      { step: 'Ngày 19-25', title: 'Pre-launch', desc: 'QA, analytics, ads setup, soft launch.' },
      { step: 'Ngày 26-30', title: 'Go-live', desc: 'Public launch, report, roadmap 90 ngày.' },
    ],
    tech: ['Next.js 15', 'Vercel', 'Midjourney', 'Runway', 'Meta Ads', 'LinkedIn Ads', 'GA4', 'Cal.com', 'Notion'],
    results: [
      'Go-live đúng ngày 30, landing Lighthouse 96 performance',
      '240+ lead qualified tháng đầu, CAC giảm 40% sau optimization tuần 2',
      'Tiết kiệm ~55% chi phí so với báo giá 3 vendor tách riêng',
      'Founder pitch demo day với brand kit & metrics thật',
    ],
    quote: {
      text: 'Là CEO startup, mình cần đối tác A-Z. Wave Digital giúp tiết kiệm thời gian và chi phí inhouse — ra mắt đúng deadline demo day.',
      author: 'CEO & Co-founder',
      company: 'Startup SaaS (NDA)',
    },
    related: ['website-travel', 'marketing-fmcg', 'agent-fintech'],
  },

  'website-ecommerce': {
    slug: 'website-ecommerce',
    category: 'Website chuyển đổi',
    title: 'Nâng cấp storefront e-commerce sang Next.js',
    subtitle: 'Core Web Vitals xanh — checkout conversion +28%',
    image: 'https://images.shadcnspace.com/assets/shadcnspace-product/templates/awake/awake-01.webp',
    client: 'Thương hiệu bán lẻ D2C (NDA)',
    industry: 'E-commerce / Retail',
    duration: '8 tuần',
    year: '2025',
    services: ['Migration', 'Next.js', 'Checkout UX', 'SEO'],
    metrics: [
      { value: '+28%', label: 'Checkout conversion' },
      { value: '95+', label: 'SEO score' },
      { value: '-38%', label: 'Cart abandonment' },
      { value: '1.2s', label: 'LCP mobile' },
    ],
    overview: 'Shop D2C doanh thu 5 tỷ/tháng nhưng Shopify theme custom phình chậm, checkout abandonment 78%. Wave Digital migrate headless Next.js, tối ưu funnel và schema product cho SEO.',
    problems: [
      'Mobile checkout abandonment 78%, payment fail không log rõ',
      'Page speed ảnh hưởng Quality Score Google Shopping',
      'Khó A/B test layout mà không dev Shopify',
      'Blog & collection SEO yếu, cannibalize keyword',
    ],
    solution: [
      'Audit funnel Hotjar + GA4, redesign checkout 1-page',
      'Headless commerce API + Next.js storefront',
      'Schema Product, Review, Breadcrumb cho rich results',
      'A/B framework built-in cho hero & CTA',
    ],
    process: [
      { step: 'Tuần 1-2', title: 'Audit', desc: 'Data funnel, tech audit, migration plan.' },
      { step: 'Tuần 3-4', title: 'Design', desc: 'PDP, PLP, checkout Figma.' },
      { step: 'Tuần 5-7', title: 'Build', desc: 'Next.js, API sync, payment gateway.' },
      { step: 'Tuần 8', title: 'Launch', desc: 'Staged rollout, 48h hypercare.' },
    ],
    tech: ['Next.js 15', 'Commerce API', 'Stripe', 'Tailwind', 'Vercel', 'GA4', 'GTM', 'Schema.org'],
    results: [
      'Checkout conversion +28%, abandonment -38%',
      'LCP mobile 1.2s, Google Shopping CPC giảm 15%',
      'SEO visibility +42% non-brand organic trong 60 ngày',
      'Team marketing tự chạy A/B hero không cần ticket dev',
    ],
    quote: {
      text: 'Storefront mới chuyên nghiệp, deploy nhanh, vận hành ổn định 100% qua sale season.',
      author: 'E-commerce Lead',
      company: 'D2C Retail (NDA)',
    },
    related: ['website-travel', 'marketing-fmcg', 'custom-logistics'],
  },

  'marketing-realestate': {
    slug: 'marketing-realestate',
    category: 'AI Marketing',
    title: 'Content & ads AI cho dự án bất động sản',
    subtitle: 'Video, image & copy đồng bộ — ROAS +32%',
    image: 'https://images.shadcnspace.com/assets/shadcnspace-product/templates/awake/awake-01.webp',
    client: 'Chủ đầu tư bất động sản (NDA)',
    industry: 'Real Estate',
    duration: '10 tuần',
    year: '2025',
    services: ['Content AI', 'TVC AI', 'Meta/Google Ads', 'Landing support'],
    metrics: [
      { value: '+32%', label: 'ROAS' },
      { value: '-45%', label: 'Time-to-publish' },
      { value: '12', label: 'Video assets / tháng' },
      { value: '180+', label: 'Lead chất lượng / tháng' },
    ],
    overview: 'Dự án căn hộ cao cấp cần flood content đa kênh (flyer, video walkthrough, ads) nhưng studio báo giá TVC vượt ngân sách 3 tháng đầu. Wave Digital sản xuất content AI có kiểm soát brand luxury và chạy performance ads.',
    problems: [
      'TVC truyền thống 80–120tr/spot, không đủ budget giai đoạn mở bán',
      'Sales cần material mới mỗi tuần theo từng căn / ưu đãi',
      'Ads creative fatigue sau 2 tuần, CPC tăng',
      'Landing không đồng bộ visual với social',
    ],
    solution: [
      'Brand film AI 60s + cut-down 15s cho Meta/TikTok',
      'Template image: căn hộ, view, tiện ích — batch 8/tháng',
      'Copy framework theo giai đoạn: awareness → conversion',
      'Sync visual với landing Wave Digital build sẵn',
    ],
    process: [
      { step: 'Tuần 1-2', title: 'Brand & Story', desc: 'Mood luxury, script, storyboard duyệt.' },
      { step: 'Tuần 3-6', title: 'Production', desc: 'AI video/image, legal disclaimer check.' },
      { step: 'Tuần 7-8', title: 'Media', desc: 'Campaign structure, pixel, lead form.' },
      { step: 'Tuần 9-10', title: 'Optimize', desc: 'Creative refresh, CPL tuning.' },
    ],
    tech: ['Runway', 'Midjourney', 'After Effects', 'Meta Ads', 'Google Ads', 'Canva Enterprise', 'GA4'],
    results: [
      'ROAS +32% vs campaign baseline trước đó',
      'Time-to-publish creative giảm 45%',
      '180+ lead chất lượng/tháng, CPL giảm 22% sau optimize',
      'Sales có kho asset refresh hàng tuần không chờ studio',
    ],
    quote: {
      text: 'TVC AI Wave Digital làm chất lượng không khác studio truyền thống — tiết kiệm ngân sách giai đoạn mở bán rất nhiều.',
      author: 'Sales & Marketing Director',
      company: 'BĐS (NDA)',
    },
    related: ['marketing-fmcg', 'website-travel', 'launching-startup'],
  },

  'agent-education': {
    slug: 'agent-education',
    category: 'AI Agent',
    title: 'Agent tư vấn khóa học cho trung tâm giáo dục',
    subtitle: 'Qualify lead 3× — tích hợp CRM & Zalo OA',
    image: 'https://images.shadcnspace.com/assets/shadcnspace-product/templates/atomist/atomist-01.webp',
    client: 'Trung tâm đào tạo / EdTech (NDA)',
    industry: 'Education',
    duration: '6 tuần',
    year: '2025',
    services: ['AI Agent', 'Zalo OA', 'CRM', 'Lịch demo'],
    metrics: [
      { value: '3×', label: 'Lead qualified' },
      { value: '24/7', label: 'Phản hồi tức thì' },
      { value: '-40%', label: 'Chi phí telesale' },
      { value: '+25%', label: 'Tỷ lệ đăng ký học' },
    ],
    overview: 'Trung tâm 8 cơ sở nhận inbox Zalo/Facebook tràn, telesale chase lead nguội. Wave Digital triển khai agent tư vấn lộ trình, báo học phí range và book lịch demo với giảng viên.',
    problems: [
      'Telesale overload 400+ lead/tuần, follow-up chậm 2–3 ngày',
      'Tư vấn viên trả lời không nhất quán về lộ trình & học phí',
      'Không track nguồn lead theo campaign',
      'Phụ huynh nhắn ngoài giờ không được phản hồi',
    ],
    solution: [
      'Agent RAG từ syllabus, học phí, lịch khai giảng',
      'Qualify: mục tiêu, trình độ, ngân sách → score lead',
      'Book demo Cal + sync CRM, notify telesale hot lead',
      'Báo cáo campaign: CPL, conversion chat → đăng ký',
    ],
    process: [
      { step: 'Tuần 1', title: 'Content Audit', desc: 'Thu thập FAQ, script tư vấn, policy.' },
      { step: 'Tuần 2-4', title: 'Build & Test', desc: 'Agent, Zalo, CRM, 150 test cases.' },
      { step: 'Tuần 5', title: 'Pilot', desc: '2 cơ sở, tune tone phụ huynh/học sinh.' },
      { step: 'Tuần 6', title: 'Rollout', desc: '8 cơ sở, training telesale handoff.' },
    ],
    tech: ['Claude API', 'Zalo OA', 'HubSpot', 'Cal.com', 'n8n', 'Google Sheets', 'Looker Studio'],
    results: [
      'Lead qualified tăng 3× nhờ phản hồi tức thì 24/7',
      'Chi phí telesale giảm 40% — focus closing thay vì FAQ',
      'Tỷ lệ đăng ký học từ lead agent +25%',
      'Dashboard nguồn lead theo campaign rõ ràng',
    ],
    quote: {
      text: 'Agent trả lời đúng lộ trình và học phí, telesale chỉ gọi lead nóng — conversion tăng rõ trong tháng đầu.',
      author: 'Operations Manager',
      company: 'EdTech (NDA)',
    },
    related: ['agent-fintech', 'marketing-fmcg', 'website-travel'],
  },
};
